# ParticleX Configuration
# https://github.com/theme-particlex/hexo-theme-particlex

# Avatar image
avatar: /images/avatar.jpg

# Home page background image
background:
    - /images/background/1.jpg
    - /images/background/2.jpeg
    - /images/background/3.jpg
    - /images/background/4.png

# Loading image
loading: /images/loading.gif

# Optional colors for category and tag
colors:
    - "#ffa2c4"
    - "#00bcd4"
    - "#03a9f4"
    - "#00a596"
    - "#ff7d73"

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com

# Main menu navigation
menu:
    "主页":
        name: house
        theme: solid
        link: /
    "关于":
        name: id-card
        theme: solid
        link: /about
    # "成就":
    #     name: star
    #     theme: solid
    #     link: /achievements
    "归档":
        name: box-archive
        theme: solid
        link: /archives
    "分类":
        name: bookmark
        theme: solid
        link: /categories
    "标签":
        name: tags
        theme: solid
        link: /tags
    "公告":
        name: sign-hanging
        theme: solid
        link: /news
    English:
      name: globe
      theme: solid
      link: /en

# Side info card
card:
    enable: true
    description: |
        Welcome! ヾ(≧O≦)〃
    iconLinks:
      -
        theme: brands
        link: https://github.com/Patrick-orz
        name: github
      -
        theme: solid
        link: https://www.luogu.com.cn/user/433153
        name: code
      -
        theme: brands
        link: https://space.bilibili.com/552260579
        name: bilibili
        
    friendLinks:

# Footer info
footer:
    since: 2023
    # Customize the server domain name ICP
    ICP:
        enable: false
        code:
        link:

# Polyfill
# https://polyfill.io
polyfill:
    enable: true
    features:
        - default

# Highlight.js
# https://highlightjs.org
highlight:
    enable: true
    style: github

# Custom toc from https://github.com/theme-particlex/hexo-theme-particlex/pull/117
toc:
    max_depth: 6
    min_depth: 1
    class: toc
    list_number: true

# Custom scroll to top button in each post
scrollTop:
  enable: true

# KaTeX math rendering
math:
    enable: true

# Image preview
preview:
    enable: true

# Article encryption
crypto:
    enable: false

# Search
search:
    enable: true

# giscus
# https://github.com/giscus/giscus
giscus:
    enable: false
    src: https://giscus.app/client.js
    repo:
    repoID:
    category:
    categoryID:
    mapping: pathname
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: bottom
    theme: preferred_color_scheme
    lang:

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
    proxy: # CORS proxy

# Waline
# https://github.com/walinejs/waline
waline:
    enable: true
    serverURL: https://waline-patrick-orz.vercel.app/ # Waline server address url, you should set this to your own link
    locale: 
        nick: '昵称'
        nickError: '昵称不能少于3个字符'
        mail: '邮箱'
        mailError: '请填写正确的邮件地址'
        link: '网址'
        optional: '可选'
        placeholder: '欢迎评论'
        sofa: '来发评论吧~'
        submit: '提交'
        like: '喜欢'
        cancelLike: '取消喜欢'
        reply: '回复'
        cancelReply: '取消回复'
        comment: '评论'
        refresh: '刷新'
        more: '加载更多...'
        preview: '预览'
        emoji: '表情'
        uploadImage: '上传图片'
        seconds: '秒前'
        minutes: '分钟前'
        hours: '小时前'
        days: '天前'
        now: '刚刚'
        uploading: '正在上传'
        login: '登录'
        logout: '退出'
        admin: '博主'
        sticky: '置顶'
        word: '字'
        wordHint: '评论字数应在 $0 到 $1 字之间！\n当前字数：$2'
        anonymous: '匿名'
        level0: '潜水'
        level1: '冒泡'
        level2: '吐槽'
        level3: '活跃'
        level4: '话痨'
        level5: '传说'
        gif: '表情包'
        gifSearchPlaceholder: '搜索表情包'
        profile: '个人资料'
        approved: '通过'
        waiting: '待审核'
        spam: '垃圾'
        unsticky: '取消置顶'
        oldest: '按倒序'
        latest: '按正序'
        hottest: '按热度'
        reactionTitle: '你认为这篇文章怎么样？'
    # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
    commentCount: true # If false, comment count will only be displayed in post page, not in home page
    pageview: true # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
    emoji: # Custom emoji
        - https://unpkg.com/@waline/emojis@1.2.0/weibo
        - https://unpkg.com/@waline/emojis@1.2.0/alus
        - https://unpkg.com/@waline/emojis@1.2.0/bilibili
        - https://unpkg.com/@waline/emojis@1.2.0/qq
        - https://unpkg.com/@waline/emojis@1.2.0/tieba
        - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
    meta: # Comment information, valid meta are nick, mail and link
        - nick
        - mail
        - link
    requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
        - nick
    lang: # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # Word limit, no limit when setting to 0
    login: enable # Whether enable login, can choose from 'enable', 'disable' and 'force'
    pageSize: 10 # Comment per page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
    enable: false
    envID:
    region:
    path: location.pathname
    lang:
